---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users/signup":
    post:
      summary: Creates a user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: user created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
                  required:
                  - email
                  - password
                  - password_confirmation
  "/users/signin":
    post:
      summary: Authenticate a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user authenticated
        '401':
          description: invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/users/signout":
    delete:
      summary: Log out a user
      tags:
      - Users
      responses:
        '204':
          description: user logged out
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
