---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  "/chat_sessions/{chat_session_id}/messages":
    get:
      summary: Fetch full message history
      tags:
      - Messages
      security:
      - bearerAuth: []
      parameters:
      - name: chat_session_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: messages retrieved
        '401':
          description: unauthorized
    post:
      summary: Send a message, get AI response
      tags:
      - Messages
      security:
      - bearerAuth: []
      parameters:
      - name: chat_session_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: message sent and AI responded
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                tone:
                  type: string
              required:
              - content
  "/chat_sessions/{chat_session_id}/suggestions":
    get:
      summary: Generate suggestions for partial content
      tags:
      - Suggestions
      security:
      - bearerAuth: []
      parameters:
      - name: chat_session_id
        in: path
        description: ID of the chat session
        required: true
        schema:
          type: string
      - name: partial_content
        in: query
        description: Partial content text
        schema:
          type: string
      responses:
        '200':
          description: Suggestions generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  suggestions:
                    type: array
                    items:
                      type: string
                required:
                - suggestions
        '422':
          description: Missing partial_content
  "/chat_sessions":
    post:
      summary: Create a new chat session (optional initial message)
      tags:
      - Messages
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: chat session created
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                initial_message:
                  type: string
                tone:
                  type: string
  "/chat_sessions/{chat_session_id}/summarize":
    post:
      summary: Summarize a chat session
      tags:
      - Messages
      security:
      - bearerAuth: []
      parameters:
      - name: chat_session_id
        in: path
        description: ChatSession ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: summary generated
  "/users/signup":
    post:
      summary: Creates a user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: user created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
                  required:
                  - email
                  - password
                  - password_confirmation
  "/users/signin":
    post:
      summary: Authenticate a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user authenticated
        '401':
          description: invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/users/signout":
    delete:
      summary: Log out a user
      tags:
      - Users
      responses:
        '204':
          description: user logged out
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
